ENTITIES = [
    {
        "name": "stores",
        "endpoint": "/stores/",
        "table": "raw.stores",
        "primary_key": "store_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
    {
        "name": "employees",
        "endpoint": "/employees/",
        "table": "raw.employees",
        "primary_key": "employee_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
    {
        "name": "payment_methods",
        "endpoint": "/payment_methods/",
        "table": "raw.payment_methods",
        "primary_key": "payment_method_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
    {
        "name": "customers",
        "endpoint": "/customers/",
        "table": "raw.customers",
        "primary_key": "customer_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
    {
        "name": "products",
        "endpoint": "/products/",
        "table": "raw.products",
        "primary_key": "product_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
    {
        "name": "orders",
        "endpoint": "/orders/",
        "table": "raw.orders",
        "primary_key": "order_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
    {
        "name": "order_items",
        "endpoint": "/order_items/",
        "table": "raw.order_items",
        "primary_key": "order_item_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
    {
        "name": "payments",
        "endpoint": "/payments/",
        "table": "raw.payments",
        "primary_key": "payment_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
    {
        "name": "inventory_movements",
        "endpoint": "/inventory_movements/",
        "table": "raw.inventory_movements",
        "primary_key": "inventory_movement_id",
        "source_key": "id",
        "source_updated_field": "updatedAt",
        "supports_incremental": True,
        "supports_pagination": True,
    },
]
